### ISSUE TITLE
Plugin no longer working in Qualtrics

### ISSUE THREAD

**Issue by ballewm** [noahfreedman/qualtrics_venn_diagram#1]
I'm a grad student looking to use this great plugin for my online survey in the next couple months, however, the plugin appears to not be working anymore on Qualtrics.  I just discovered this a few days ago and cannot figure out why.  I do not have much experience in coding, though, it does seem like the problem is more on the Qualtrics side of things.  What could be the problem?  Thank you!

**Comment by noahfreedman** [comment]
Hi,

I can take a look and see if it is still working. If qualtrics has changed
their front-end it may need revision.

Can you send me a link to the qualtrics survey that you are using with the
plugin?

Best,

Noah

**Comment by ballewm** [comment]
https://cgu.co1.qualtrics.com/SE/?SID=SV_9zR0U7IFl4oBY6F

It will be the first and only question (I copied it from the survey).

Thank you!

Matt

**Comment by noahfreedman** [comment]
Hi Matt,

One of my servers was down. I just booted it up, and the link you sent is
now working, let me know if it works for you now as well.

Cheers,

Noah

**Comment by ballewm** [comment]
Excellent!  It is working.

Thank you, Noah.

Best,

Matt

**Comment by ballewm** [comment]
Hi Noah,

I believe that we may be experiencing the same problem as before--the plug-in is not loading.  Do you think one of the servers might be down?

Best,

Matt

**Comment by noahfreedman** [comment]
Thanks, it looks like the whole server is down. It may be maintenance over the break. I will check when I am back on campus on Monday.

**Comment by ballewm** [comment]
Great!  Thank you--it is working now.

**Comment by noahfreedman** [comment]
The server is back online
